//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanningDBEntities : DbContext
    {
        public PlanningDBEntities()
            : base("name=PlanningDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCH> BRANCHES { get; set; }
        public virtual DbSet<DIRECTION> DIRECTIONS { get; set; }
        public virtual DbSet<job_info> job_info { get; set; }
        public virtual DbSet<leader> leaders { get; set; }
        public virtual DbSet<MISSION> MISSIONs { get; set; }
        public virtual DbSet<NOBTE> NOBTEs { get; set; }
        public virtual DbSet<NOBTE_EXCHANGE> NOBTE_EXCHANGE { get; set; }
        public virtual DbSet<OFFICER> OFFICERs { get; set; }
        public virtual DbSet<SECTION> SECTIONS { get; set; }
        public virtual DbSet<SECTOR> SECTORS { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<Tmam> Tmams { get; set; }
        public virtual DbSet<TmamType> TmamTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VACATION> VACATIONs { get; set; }
        public virtual DbSet<WEAPON> WEAPONS { get; set; }
        public virtual DbSet<ImagesHome> ImagesHomes { get; set; }
    }
}
